# Generated by Django 5.0 on 2024-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='works',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
    ]
