# Generated by Django 5.0 on 2024-03-22 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
                ('image', models.ImageField(upload_to='service/images/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('skills', models.IntegerField(default=0, verbose_name='классность')),
                ('photo', models.ImageField(default='user-default.png', upload_to='static/service/', verbose_name='фотографии')),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='вид услуг')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-vote_ratio', '-vote_total', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='дата записи')),
                ('time', models.TimeField(unique=True, verbose_name='время записи')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='заявитель')),
                ('works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.works', verbose_name='вид работ')),
                ('service', models.ManyToManyField(to='service.service', verbose_name='вид услуг')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.staff', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('order_text', models.TextField(verbose_name='Описание заказа')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.statusorder', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='отзыв')),
                ('value', models.CharField(choices=[('положительный', 'Положительный'), ('отрицательный', 'Отрицательный')], max_length=100, verbose_name='отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.staff', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('owner', 'staff')},
            },
        ),
    ]
