# Generated by Django 5.0 on 2024-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=200, verbose_name='клиент')),
                ('rec_day', models.DateField(verbose_name='дата')),
                ('rec_time', models.TimeField(verbose_name='время')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name'], 'verbose_name': 'сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
