# Generated by Django 5.0 on 2024-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rec_alter_recording_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
